substitutions:
  roomname: roomname
 
esphome:
  name: $roomname
  platform: ESP32
  board: esp32doit-devkit-v1 # or change for appropriate board this recommended for PCB

wifi:
  ssid: "ssid" #Change as required
  password: "password" #Change as required
  
  ap:
    ssid: ESPHome $roomname
    password: "bedsensor" #Change as required
  
  manual_ip: #enter static ip and network - staic ip recommended
    static_ip: ###.###.###.###
    gateway: ###.###.###.###
    subnet: ###.###.###.###
  
captive_portal:
logger:
api:
ota:
web_server:

# i2c required for BMP280 sensor, can use other i2c devices with appropriate changes
i2c:
  sda: 21 #ESP32 pin correct for PCB
  scl: 22 #ESP32 pin correct for PCB
  scan: true
  
# Buttons not needed but allow for remote restart and safe mode
button:
  - platform: restart
    name: "Bedsensor Restart"
  - platform: safe_mode
    name: "Bedsensor (Safe Mode)"
          
sensor:
#Bed sensor section
  - platform: adc
    pin: GPIO34 #ADC pin on ESP32 correct for PCB
    attenuation: 11db
    name: "Left Bed Sensor"
    id: "Left_bed_sensor"
    icon: mdi:bed
    update_interval: 0.5s
    filters:
      - sliding_window_moving_average:
          window_size: 10
          send_every: 1
      - or:
          - throttle: 180s
          - delta: 0.02
  - platform: adc
    pin: GPIO35 #ADC pin on ESP32 correct for PCB
    attenuation: 11db
    name: "Right Bed Sensor"
    id: "Right_bed_sensor"
    icon: mdi:bed
    update_interval: 0.5s
    filters:
      - sliding_window_moving_average:
          window_size: 10
          send_every: 1
      - or:
          - throttle: 180s
          - delta: 0.02
#BMP280 section or replace eith alternate i2C device
  - platform: bmp280
    temperature:
      name: "Bedroom Temperature"
      id: bmp280_temperature
    pressure:
      name: "Bedroom Air Pressure"
      id: bmp280_pressure
    address: 0x76
    update_interval: 15s
# Wifi signal and uptime - not needed but nice to have
  - platform: wifi_signal
    name: "Bedsensor WiFi Signal"
    update_interval: 300s
  - platform: uptime # converted by text sensor into readable form
    name: Uptime Sensor
    update_interval: 113s
    id: uptime_sec
    
text_sensor:
# Makes readable uptime
  - platform: template 
    name: Bedsensor Uptime
    lambda: |-
      int seconds = (id(uptime_sec).state);
      int days = seconds / (24 * 3600);
      seconds = seconds % (24 * 3600); 
      int hours = seconds / 3600;
      seconds = seconds % 3600;
      int minutes = seconds /  60;
      seconds = seconds % 60;
      return { (String(days) +"d " + String(hours) +"h " + String(minutes) +"m "+ String(seconds) +"s").c_str() };
    icon: mdi:clock-start
    update_interval: 113s

# Gives IP and SSID info if needed
  - platform: wifi_info
    ip_address:
      name: Bedsensor IP Address
      id: bedsensorip
    ssid:
      name: Bedsensor SSID
      id: bedsensorssid

# Bed occupancy
binary_sensor:
  - platform: template
    name: "Left Bed Occupied"
    device_class: occupancy
    id: leftoccupancy
    # Checks to see if voltage is lower than the left trigger level, if so it sets left bed side to occupied
    lambda: |-
      if (id(Left_bed_sensor).state < id(Left_bed_trigger_level).state) {
        return true;
      } else {
        return false;
      }
  - platform: template
    name: "Right Bed Occupied"
    id: rightoccupancy
    # Checks to see if voltage is lower than the right trigger level, if so it sets right bed side to occupied
    device_class: occupancy
    lambda: |-
      if (id(Right_bed_sensor).state < id(Right_bed_trigger_level).state) {
        return true;
      } else {
        return false;
      }

# Adds two settings for bed trigger level
number:
  - platform: template
    name: "Left Bed Trigger Level"
    id: "Left_bed_trigger_level"
    optimistic: true
    min_value: 0
    max_value: 3.5
    step: 0.05
    icon: mdi:arrow-collapse-down
    unit_of_measurement: V 
  - platform: template
    name: "Right Bed Trigger Level"
    id: "Right_bed_trigger_level"
    optimistic: true
    min_value: 0
    max_value: 3.5
    step: 0.05
    icon: mdi:arrow-collapse-down
    unit_of_measurement: V
